language: python

install:
  - deactivate
  # Do not buffer python outputs; flush them directly to the terminal
  - export PYTHONUNBUFFERED=true
  # Sets up a miniconda environment
  - source devtools/ci/install.sh
  = conda install --yes conda-build
  - conda build --quiet devtools/conda-recipe
  - conda create --quiet --yes --name test --use-local openpathsampling-dev
  - source activate test
  - conda info --envs
  - conda install --quiet --yes msmbuilder
  - conda install --quiet --yes nose python-coveralls ipynbtest
  - conda update --all --yes --use-local --quiet

script:
  - python --version
  - source devtools/ci/git_hash.sh
  #- echo "Building OPS (with conda)" && echo -en 'travis_fold:start:build\\r'
  #- echo -en 'travis_fold:end:build\\r'

  # Run tests in test environment
  #- echo "Create test environment" && echo -en 'travis_fold:start:create_env\\r'
  #- echo -en 'travisfold:end:create_env\\r'
  - conda list -n test
  #- conda install --yes future
  #- conda install --yes jupyter nose nose-timer python-coveralls msmbuilder pyemma #ipynbtest
  - source devtools/ci/nosetests.sh
  - if [ ${CONDA_PY:0:1} -eq "2" ]; then source devtools/ci/ipythontests.sh; fi
  #- source devtools/ci/ipythontests.sh

  # Upload new docs
  - bash -x devtools/ci/after_sucess.sh

addons:
  apt:
    packages:
    - pandoc

env:
  global:
    - secure: "NJvoSrLNd2ZR3HluJjEqI36gD5lsucwIvgnYjNmM4cwnnA77aLV9FRYTwlLRZn3XY9FL8KOzL5l0amNzMD7sQrf7bWwWv7iCUBddH549q9RSgiuOugtodYJ6VaXi76hk1rOgcJpDoCj9wTCIlMtWibPUzr1QHmdihfdM2iA2kkE="
    - secure: "l9NJkZDD0ALhkErUvhRrreLsrcWErd+CXpWv8dxHGtkjemNx6CwVtyL+a30jz/QwMANSZbKll/cPK5yJQvuwDaWxja6UPLLKVNGtma+CmwKcIC/wwTwbMoxcS62fyLJ3kS0qR8oCQz2nCPKiYyRGADtPLWVMZckY1SJfNYcKuCM="
    - secure: "kb37xmsSV3pEnESnINzwlW2Cju/UFzA/G+m+NsihAwO8RMPZwKCrZK/rptgkUDACXJxom5M690WEukQkHnOt+OTrWhu7WKZgYeVuWUs2++RohYv/m5npaOHMMn+uYmF328v4PvPmXxbD02zzg5Tgdn82x8oa6J8BKX8ohOQ6Xpg="
  matrix:
    - CONDA_PY=2.7
    - CONDA_PY=3.5
    - CONDA_PY=3.6
