language: python
python:
- '2.7'
install:
- deactivate
- source devtools/ci/install.sh
- export PYTHONUNBUFFERED=true
script:
- echo travis_fold:start:conda.build.package
- conda install --yes conda-build
- conda build devtools/conda-recipe
- echo travis_fold:end:conda.build.package
- source activate _test
- source devtools/ci/git_hash.sh
- source devtools/ci/nosetests.sh
- source devtools/ci/ipythontests.sh
- bash -x devtools/ci/after_sucess.sh
env:
  matrix:
  - python=2.7  CONDA_PY=27  CONDA_NPY=110
  global:
  - secure: kb37xmsSV3pEnESnINzwlW2Cju/UFzA/G+m+NsihAwO8RMPZwKCrZK/rptgkUDACXJxom5M690WEukQkHnOt+OTrWhu7WKZgYeVuWUs2++RohYv/m5npaOHMMn+uYmF328v4PvPmXxbD02zzg5Tgdn82x8oa6J8BKX8ohOQ6Xpg=
