package:
  name: openpathsampling-dev
  version: "0.0.3"

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - numpy
    - setuptools
    - numpy
    - scipy
    - setuptools
    - netcdf4
    - openmm
    - openmmtools
    - pymbar
    - docopt
    - jinja2
    - mdtraj
    - svgwrite
    - networkx
    - matplotlib
    - ipynbtest

  run:
    - python
    - pandas
    - numpy
    - scipy
    - netcdf4
    - openmm
    - openmmtools
    - pymbar
    - docopt
    - pyyaml
    - jinja2
    - mdtraj
    - svgwrite
    - networkx
    - matplotlib
    - msmbuilder
    - pyemma
    - ipynbtest

about:
  home: https://github.com/choderalab/openpathsampling
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
