package:
  name: openpathsampling-dev
  version: !!str 0.0.1

requirements:
  build:
    - python
    - numpy
#    - mdtraj
#    - openmm
    - setuptools

  run:
    - python
    - pandas
    - numpy
    - scipy
    - netcdf4
    - openmm
    - openmmtools
    - pymbar
    - docopt
    - pyyaml
    - jinja2

about:
  home: https://github.com/choderalab/openpathsampling
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
