package:
  name: opentis
  version: !!str dev

build:
  entry_points:
    - mdconvert = mdtraj.scripts.mdconvert:entry_point
    - mdinspect = mdtraj.scripts.mdinspect:entry_point

requirements:
  build:
    - python
    - numpy
    - mdtraj
    - openmm
    - setuptools

  run:
    - python
    - openmm
    - mdtraj

about:
  home: https://github.com/choderalab/msm-tis
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
